name: .NET

on:
  push:
    tags: releases/[0-9]+.[0-9]+.[0-9]+
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Get version
      id: get-version
      if: startsWith( github.ref, 'refs/tags/releases/')
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/releases/}
    - name: Create package
      if: startsWith( github.ref, 'refs/tags/releases/')
      run: dotnet pack --include-symbols --include-source --configuration Release /p:Version=${{ steps.get-version.outputs.VERSION }} --output nupkgs
    - name: Publish to nuget.org
      if: startsWith( github.ref, 'refs/tags/releases/')
      run: dotnet nuget push nupkgs/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: needs-a-token-here
